[build]
publish = "public"
command = "hugo --theme=hugo-theme-cleanwhite --buildDrafts --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
